Add bookings
ldv2018/java-shareit pull request #3
Opened 2023-03-12 14:31 UTC by ldv2018

2023-03-13 20:19 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-03-13 20:19 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        bookingValidator.check(bookingRequestDto);
Ну если у тебя есть отдельный класс для валидации, ну и унеси уже туда и проверку на пустой запрос!

2023-03-13 20:19 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        for (Booking b : bookings) {
Перепиши это через `stream()`
Буквально в одну строку, начиная сразу с `return` !

2023-03-13 20:19 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            booking.setStatus(approved ? Status.APPROVED : Status.REJECTED);
Можно предварительно заимпортить статические переменные и получить более лаконичный и читаемый код
`booking.setStatus(approved ? APPROVED : REJECTED);`

2023-03-13 20:19 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            throw new NotFoundException("у пользователя нет доступа к бронированию");
У какого пользователя??
Давай больше инфы в логи и тем более в ошибки!

2023-03-13 20:19 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    @Query("select i from Item i " +
Оформляй SQL запросы. Пиши спец. слова в верхнем регистре: `CREATE`, `FROM`, `AND`

2023-03-13 20:19 UTC, FanaticFiz commented on src/main/resources/application.properties
> +#db.name=shareit
удаляем

2023-03-13 20:19 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    status text,
Почему у тебя все поля `text` ?
Это ест много памяти в БД. Нужно с умом подходить к этому вопросу.
Вот например статус, ему едва ли надо 20 символов и это куда более экономно чем безграничный text

2023-03-13 20:19 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS requests (
Не помешает выравнивание!

```
CREATE TABLE IF NOT EXISTS requests
(
    request_id  int auto_increment,
    description text,
    requester   int, --user
    created     date,
    CONSTRAINT pk_request PRIMARY KEY (request_id)
);
```

2023-03-14 19:07 UTC, ldv2018 commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    @Query("select i from Item i " +
Они сами так пишут, в начале 3-й страницы. https://code.s3.yandex.net/Java/4mod15sprProject/mentors_advice_02.12.22.pdf

2023-03-14 19:08 UTC, ldv2018 commented on src/main/resources/application.properties
> +#db.name=shareit
Это мне надо)

2023-03-14 19:25 UTC, ldv2018 commented on src/main/resources/schema.sql
> +    status text,
Я считал что они не влияют на размер. https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_varchar.28n.29_by_default

2023-03-15 08:01 UTC, fizanatic commented on src/main/resources/schema.sql
> +    status text,
Отлично что ты это читал! 
varchar (without the (n)) or text are similar, but without the length limit. 

Но почему ты пропускаешь это
If what you really need is a text field with an length limit then varchar(n) is great

И поле статус это именно тот случай. Это не фамилия где нужно думать о том что они бывают разные...

2023-03-15 08:04 UTC, fizanatic commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    @Query("select i from Item i " +
Команды бывают разные. 
У меня на разных проектах, было принято оформлять именно так, соответственно и тебе рекомендую...

2023-03-15 12:28 UTC, ldv2018 commented on src/main/resources/schema.sql
> +    status text,
Я согласен, но я решил что у меня нет really need :) Если бы был gui, где был, например, выпадающий список со статусами и там, что бы никто случайно, добавив новый статус, не сделал так, что бы название статуса перестало помещаться в поле или поле бы растянулось на пол экрана - тогда да, его длину можно сразу ограничить.

2023-03-15 12:32 UTC, fizanatic commented on src/main/resources/schema.sql
> +    status text,
Да я в целом не против, главное чтобы ты понимал что делаешь.
Сейчас я вижу, что в этом вопросе у тебя полный порядок.

2023-03-16 17:56 UTC, FanaticFiz approved these changes

2023-03-25 17:30 UTC, merged