Add item requests
ldv2018/java-shareit pull request #4
Opened 2023-03-25 17:28 UTC by ldv2018

2023-03-26 21:35 UTC, FanaticFiz requested changes

2023-03-26 21:35 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        bookingValidator.check(bookingRequestDto);
Если метод построен на том что он кидается исключениями, то лучше его так и назвать `throwIfNotValid`.

2023-03-26 21:35 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        User user = userStorage.findById(id)
Переменная `User user` не используется

2023-03-26 21:35 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +import javax.validation.constraints.NotBlank;
А почему валидация в модели `entity`, а не `dto` ?
Почему класс расположен не в пакете `model`, как в других сущностях?

2023-03-26 21:35 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    @GetMapping("all")
Что это за второй маппинг `all` ? 

На входе тот же userId, только с пагинацией, почему это не один метод?
Пересмотри, тут чтот странное...

2023-03-26 21:35 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +    Page<ItemRequest> findAll(int userID, Pageable pageable);
`userID` не корректно!   ->  `userId`

2023-03-26 21:52 UTC, ldv2018 commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    @GetMapping("all")
Привет. Там первый GET /requests - он возвращает список своих запросов. GET /requests/all?from={from}&size={size} - возвращает список, созданных другими пользователями. По заданию такие эндпойнты указаны.

2023-03-26 21:53 UTC, ldv2018 commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +    Page<ItemRequest> findAll(int userID, Pageable pageable);
🤦‍♂️

2023-03-27 06:21 UTC, fizanatic commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    @GetMapping("all")
Явно укажи `/`

`"/all"`

2023-03-27 18:01 UTC, FanaticFiz approved these changes

2023-03-27 18:14 UTC, merged